### ISSUE TITLE
Material uses deprecated methods on android api 35

### ISSUE THREAD

**Issue by LoveMyBaby** [material-components/material-components-android#4507]
**com.google.android.material:material：1.12.0**

**Is your feature request related to a problem? Please describe.**
When I adapted EdgeToEdge to publish to the Play Store, I received a prompt:
your app uses deprecated APIs or parameters for borderless design
One or more APIs you used or parameters you set for borderless design and window display have been deprecated in Android 15. Your app uses the following deprecated APIs or parameters:
**android.view.Window.setStatusBarColor
android.view.Window.setNavigationBarColor
LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES**
These APIs or parameters start at the following location: com.google.android.material.datepicker.MaterialDatePicker.onStart

**Describe the solution you'd like**
Please fix it

**Comment by ytheekshana** [comment]
+1

**Comment by RoyTheReal** [comment]
Same issue with me

**Comment by carlota-may** [comment]
+1

**Comment by michael-winkler** [comment]
+1

**Comment by liyuhaolol** [comment]
+1

**Comment by JuanZurit** [comment]
+1

**Comment by jared-loseit** [comment]
+1

**Comment by ihavryliuk-iqmessenger** [comment]
+1

**Comment by LoveMyBaby** [comment]
Official fixes have been made in version [1.14.0-alpha01]( https://github.com/material-components/material-components-android/releases/tag/1.14.0-alpha01)

**Comment by chris-cprosoft** [comment]
Using version 1.14.0-alpha01 and upload this to Google Play still gives me:

```
Your app uses deprecated APIs or parameters for edge-to-edge
One or more of the APIs you use or parameters that you set for edge-to-edge and window display have been deprecated in Android 15. Your app uses the following deprecated APIs or parameters:

android.view.Window.setStatusBarColor
android.view.Window.setNavigationBarColor

These start in the following places:

com.google.android.material.bottomsheet.a.onCreate
com.google.android.material.internal.c.a

To fix this, migrate away from these APIs or parameters.
```

Even tough 1.14.0-alpha01 release notes mention "BottomSheet Deprecated enableEdgeToEdge for bottom sheet dialogs on API 35+. (https://github.com/material-components/material-components-android/commit/603f1ef9d5223fc06fa432c4175473eda2138330)" this seems not to be resolved.

**Comment by hunterstich** [comment]
Hi, 

Sorry! This was fixed and then reverted in https://github.com/material-components/material-components-android/commit/aaa40dbc4e217103a9d05425e27548beee3394d0 after causing a few issues.

We're working on how to fix this moving forward while not triggering Play's static analysis and not breaking existing behavior. Thanks for the patience!

**Comment by Bykhkalo** [comment]
+1

**Comment by samsonpaul87** [comment]
+1

**Comment by samsonpaul87** [comment]
@LoveMyBaby , @hunterstich 

I noticed the ticket was marked as resolved and closed, stating that the fix is available in version [1.14.0-alpha01](https://github.com/material-components/material-components-android/releases/tag/1.14.0-alpha01). However, the warning still persists in the latest release (e.g., [1.13.0-alpha14](https://github.com/material-components/material-components-android/releases/tag/1.13.0-alpha14)). I have verified this in my app, and it seems the underlying issue remains.

I can also see that others have commented similarly.

Could you please consider reopening this ticket or let me know if a new one should be created to track the ongoing issue?

Thanks!

**Comment by giveappsoficial** [comment]
+1

**Comment by Distantman** [comment]
+1

**Comment by 0xDOM** [comment]
+1

**Comment by paperrose** [comment]
+1

**Comment by dmitriy-chernysh** [comment]
+1

**Comment by noxo** [comment]
+1

MaterialDatePicker.onStart() is using EdgeToEdgeUtils.applyEdgeToEdge() which is using deprecated methods
[window.setStatusBarColor(statusBarColor);](https://github.com/material-components/material-components-android/blob/3c332f9a276c68fe37de24ee662ecb70f15db70f/lib/java/com/google/android/material/internal/EdgeToEdgeUtils.java#L97)
[window.setNavigationBarColor(navigationBarColor);](https://github.com/material-components/material-components-android/blob/3c332f9a276c68fe37de24ee662ecb70f15db70f/lib/java/com/google/android/material/internal/EdgeToEdgeUtils.java#L98)

**Comment by zipswich** [comment]
We are still getting the following from Google Play Console:
```
Your app uses deprecated APIs or parameters for edge-to-edge
One or more of the APIs you use or parameters that you set for edge-to-edge and window display have been deprecated in Android 15. Your app uses the following deprecated APIs or parameters:

android.view.Window.setStatusBarColor
android.view.Window.setNavigationBarColor
These start in the following places:

com.google.android.material.bottomsheet.BottomSheetDialog.onCreate
com.google.android.material.internal.EdgeToEdgeUtils.applyEdgeToEdge
com.google.android.material.sidesheet.b.onCreate
```
The app uses com.google.android.material:material:1.13.0.

Should I open another issue to report this?

**Comment by noxo** [comment]
> The app uses com.google.android.material:material:1.13.0. 
> Should I open another issue to report this?

@zipswich c2051db which fixes this, is only in master / 1.14 (still alpha)..

**Comment by zipswich** [comment]
> [@zipswich](https://github.com/zipswich) [c2051db](https://github.com/material-components/material-components-android/commit/c2051db2a9be2a1e23f1128bfc76a9ff29ede7c4) which fixes this, is only in master / 1.14 (still alpha)..

Thank you. It was committed half a year ago. The cycle length surprised me.

**Comment by renatoresende** [comment]
+1
