### ISSUE TITLE
TextInputEditText losing focus 

### ISSUE THREAD

**Issue by devqmr** [material-components/material-components-android#500]
**Description:** TextInputEditText where the inputType="numberDecimal"  inside ReyclerView item losing focus after keyboard popup so user can not enter any number value.

**Expected behavior:** User can enter numbers without any problem
https://youtu.be/qt21EWerrLI

**Source code:** 
`<com.google.android.material.textfield.TextInputLayout
        android:id="@+id/itemDeliveredOrder_til_amount"
        style="@style/DeliveredOrderTextInputLayoutStyle"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="16dp"
        android:layout_marginEnd="16dp"
        app:layout_constraintEnd_toStartOf="@+id/guideline3"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">`
`<com.google.android.material.textfield.TextInputEditText
            android:id="@+id/itemDeliveredOrder_tie_amount"
            style="@style/DeliveredOrderTextInputLayoutStyle"
            android:layout_width="match_parent"
            android:imeOptions="actionDone"
            android:layout_height="wrap_content"
            android:hint="@string/amount"
            android:inputType="numberDecimal" />
    </com.google.android.material.textfield.TextInputLayout>`

**Android API version:** Android API version here

**Material Library version:**  1.1.0-alpha08 & 1.1.0-alpha09

**Device:** Galaxy Note 9 (SM-N960F/DS)

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

**Comment by jadroa** [comment]
This is still happening when com.google.android.material.textfield.TextInputLayout used inside viewpager2 based on recyclerview.
Its not only inputType number, but for all inputTypes on first focus and when focus change from one TextInputEditText to another TextInputEditText with different inputTypes, then the focus is lost.

"com.google.android.material:material:1.2.0-alpha01"
"androidx.viewpager2:viewpager2:1.0.0"

**Comment by joost-klitsie** [comment]
I think this is due to the fact that the request focus that happens on the text input field will trigger a re-layout of the recyclerview, which in term triggers a scroll event with 0 dx.
In this the ViewPager2 assumes with the comment: 
// onScrolled while IDLE means RV has just been populated after an adapter has been set.
// Contract requires us to fire onPageSelected as well.
Which is of course bs. So this triggers the onPageSelected which in turn calls this magical OnPageChangeCallback:
        // Prevents focus from remaining on a no-longer visible page
        final OnPageChangeCallback focusClearer = new OnPageChangeCallback() {
            @Override
            public void onPageSelected(int position) {
                clearFocus();
                if (hasFocus()) { // if clear focus did not succeed
                    mRecyclerView.requestFocus(View.FOCUS_FORWARD);
                }
            }
        };

**Comment by joost-klitsie** [comment]
Okay I came up with the ugliest workaround. This could 

1. clear the scroll listeners from the recyclerview. You can access the viewPager2's recyclerview as it is its first child.
2. add your own adjusted scroll listener copy pasted from the viewpager2 recycler, where you remove the code underneath the comment // onScrolled while IDLE means RV has just been populated after an adapter has been set. I copy paste it in here
3. Register your own data observer to your adapter, that triggers the update as how you see fit when the recyclerview is updated.

```

        myViewPager2.apply {
            adapter = // Some adapter you have
                (children.first() as RecyclerView).also {
                    it.clearOnScrollListeners()
                    it.addOnScrollListener(NotTriggeringUnnecessaryUpdateScrollListener(this))
                }
            (adapter as? RecyclerView.Adapter)?.registerAdapterDataObserver(object :
                RecyclerView.AdapterDataObserver() {

                override fun onItemRangeRemoved(positionStart: Int, itemCount: Int) {
                    currentItem = currentItem
                }

                override fun onItemRangeMoved(fromPosition: Int, toPosition: Int, itemCount: Int) {
                    currentItem = currentItem
                }

                override fun onItemRangeInserted(positionStart: Int, itemCount: Int) {
                    currentItem = currentItem
                }

                override fun onItemRangeChanged(positionStart: Int, itemCount: Int) {
                    currentItem = currentItem
                }

                override fun onItemRangeChanged(positionStart: Int, itemCount: Int, payload: Any?) {
                    currentItem = currentItem
                }
            })
        }
```

```

class NotTriggeringUnnecessaryUpdateScrollListener(private val mViewPager: ViewPager2) :
    RecyclerView.OnScrollListener() {
    /** @hide
     */
    @Retention(RetentionPolicy.SOURCE)
    @IntDef(
        STATE_IDLE,
        STATE_IN_PROGRESS_MANUAL_DRAG,
        STATE_IN_PROGRESS_SMOOTH_SCROLL,
        STATE_IN_PROGRESS_IMMEDIATE_SCROLL,
        STATE_IN_PROGRESS_FAKE_DRAG
    )
    private annotation class AdapterState()

    private var mCallback: OnPageChangeCallback? = null
    private val mRecyclerView: RecyclerView = mViewPager.children.first() as RecyclerView
    private val mLayoutManager: LinearLayoutManager

    // state related fields
    @AdapterState
    private var mAdapterState: Int = 0

    @ScrollState
    var scrollState: Int = 0
        private set
    private val mScrollValues: ScrollEventValues
    private var mDragStartPosition: Int = 0
    private var mTarget: Int = 0
    private var mDispatchSelected: Boolean = false
    private var mScrollHappened: Boolean = false
    private var mDataSetChangeHappened: Boolean = false

    /**
     * @return `true` if a fake drag is ongoing. Returns `false` from the moment the
     * [ViewPager2.endFakeDrag] is called.
     */
    var isFakeDragging: Boolean = false
        private set

    private fun resetState() {
        mAdapterState = STATE_IDLE
        scrollState = ViewPager2.SCROLL_STATE_IDLE
        mScrollValues.reset()
        mDragStartPosition = NO_POSITION
        mTarget = NO_POSITION
        mDispatchSelected = false
        mScrollHappened = false
        isFakeDragging = false
        mDataSetChangeHappened = false
    }

    /**
     * This method only deals with some cases of [AdapterState] transitions. The rest of
     * the state transition implementation is in the [.onScrolled] method.
     */
    override fun onScrollStateChanged(
        recyclerView: RecyclerView,
        newState: Int
    ) {
        // User started a drag (not dragging -> dragging)
        if (((mAdapterState != STATE_IN_PROGRESS_MANUAL_DRAG
                    || scrollState != ViewPager2.SCROLL_STATE_DRAGGING)
                    && newState == RecyclerView.SCROLL_STATE_DRAGGING)
        ) {
            startDrag(false)
            return
        }

        // Drag is released, RecyclerView is snapping to page (dragging -> settling)
        // Note that mAdapterState is not updated, to remember we were dragging when settling
        if (isInAnyDraggingState && newState == RecyclerView.SCROLL_STATE_SETTLING) {
            // Only go through the settling phase if the drag actually moved the page
            if (mScrollHappened) {
                dispatchStateChanged(ViewPager2.SCROLL_STATE_SETTLING)
                // Determine target page and dispatch onPageSelected on next scroll event
                mDispatchSelected = true
            }
            return
        }

        // Drag is finished (dragging || settling -> idle)
        if (isInAnyDraggingState && newState == RecyclerView.SCROLL_STATE_IDLE) {
            var dispatchIdle: Boolean = false
            updateScrollEventValues()
            if (!mScrollHappened) {
                // Pages didn't move during drag, so either we're at the start or end of the list,
                // or there are no pages at all.
                // In the first case, ViewPager's contract requires at least one scroll event.
                // In the second case, don't send that scroll event
                if (mScrollValues.mPosition != RecyclerView.NO_POSITION) {
                    dispatchScrolled(mScrollValues.mPosition, 0f, 0)
                }
                dispatchIdle = true
            } else if (mScrollValues.mOffsetPx == 0) {
                // Normally we dispatch the selected page and go to idle in onScrolled when
                // mOffsetPx == 0, but in this case the drag was still ongoing when onScrolled was
                // called, so that didn't happen. And since mOffsetPx == 0, there will be no further
                // scroll events, so fire the onPageSelected event and go to idle now.
                // Note that if we _did_ go to idle in that last onScrolled event, this code will
                // not be executed because mAdapterState has been reset to STATE_IDLE.
                dispatchIdle = true
                if (mDragStartPosition != mScrollValues.mPosition) {
                    dispatchSelected(mScrollValues.mPosition)
                }
            }
            if (dispatchIdle) {
                // Normally idle is fired in last onScrolled call, but either onScrolled was never
                // called, or we were still dragging when the last onScrolled was called
                dispatchStateChanged(ViewPager2.SCROLL_STATE_IDLE)
                resetState()
            }
        }
        if ((mAdapterState == STATE_IN_PROGRESS_SMOOTH_SCROLL
                    ) && (newState == RecyclerView.SCROLL_STATE_IDLE) && mDataSetChangeHappened
        ) {
            updateScrollEventValues()
            if (mScrollValues.mOffsetPx == 0) {
                if (mTarget != mScrollValues.mPosition) {
                    dispatchSelected(
                        if (mScrollValues.mPosition == NO_POSITION) 0 else mScrollValues.mPosition
                    )
                }
                dispatchStateChanged(ViewPager2.SCROLL_STATE_IDLE)
                resetState()
            }
        }
    }

    /**
     * This method only deals with some cases of [AdapterState] transitions. The rest of
     * the state transition implementation is in the [.onScrollStateChanged] method.
     */
    override fun onScrolled(recyclerView: RecyclerView, dx: Int, dy: Int) {
        mScrollHappened = true
        updateScrollEventValues()
        if (mDispatchSelected) {
            // Drag started settling, need to calculate target page and dispatch onPageSelected now
            mDispatchSelected = false
            val scrollingForward: Boolean =
                dy > 0 || (dy == 0 && dx < 0 == (mViewPager.layoutDirection == LAYOUT_DIRECTION_RTL))

            // "&& values.mOffsetPx != 0": filters special case where we're scrolling forward and
            // the first scroll event after settling already got us at the target
            mTarget =
                if (scrollingForward && mScrollValues.mOffsetPx != 0) mScrollValues.mPosition + 1 else mScrollValues.mPosition
            if (mDragStartPosition != mTarget) {
                dispatchSelected(mTarget)
            }
        } else if (mAdapterState == STATE_IDLE) {
            // onScrolled while IDLE means RV has just been populated after an adapter has been set.
            // Contract requires us to fire onPageSelected as well.
        }

        // If position = -1, there are no items. Contract says to send position = 0 instead.
        dispatchScrolled(
            if (mScrollValues.mPosition == NO_POSITION) 0 else mScrollValues.mPosition,
            mScrollValues.mOffset, mScrollValues.mOffsetPx
        )

        // Dispatch idle in onScrolled instead of in onScrollStateChanged because RecyclerView
        // doesn't send IDLE event when using setCurrentItem(x, false)
        if (((mScrollValues.mPosition == mTarget || mTarget == NO_POSITION)
                    && (mScrollValues.mOffsetPx == 0) && !(scrollState == ViewPager2.SCROLL_STATE_DRAGGING))
        ) {
            // When the target page is reached and the user is not dragging anymore, we're settled,
            // so go to idle.
            // Special case and a bit of a hack when mTarget == NO_POSITION: RecyclerView is being
            // initialized and fires a single scroll event. This flags mScrollHappened, so we need
            // to reset our state. However, we don't want to dispatch idle. But that won't happen;
            // because we were already idle.
            dispatchStateChanged(ViewPager2.SCROLL_STATE_IDLE)
            resetState()
        }
    }

    /**
     * Calculates the current position and the offset (as a percentage and in pixels) of that
     * position from the center.
     */
    private fun updateScrollEventValues() {
        val values: ScrollEventValues = mScrollValues
        values.mPosition = mLayoutManager.findFirstVisibleItemPosition()
        if (values.mPosition == RecyclerView.NO_POSITION) {
            values.reset()
            return
        }
        val firstVisibleView: View? =
            mLayoutManager.findViewByPosition(values.mPosition)
        if (firstVisibleView == null) {
            values.reset()
            return
        }
        var leftDecorations: Int = mLayoutManager.getLeftDecorationWidth(firstVisibleView)
        var rightDecorations: Int = mLayoutManager.getRightDecorationWidth(firstVisibleView)
        var topDecorations: Int = mLayoutManager.getTopDecorationHeight(firstVisibleView)
        var bottomDecorations: Int = mLayoutManager.getBottomDecorationHeight(firstVisibleView)
        val params: ViewGroup.LayoutParams = firstVisibleView.layoutParams
        if (params is MarginLayoutParams) {
            val margin: MarginLayoutParams = params
            leftDecorations += margin.leftMargin
            rightDecorations += margin.rightMargin
            topDecorations += margin.topMargin
            bottomDecorations += margin.bottomMargin
        }
        val decoratedHeight: Int = firstVisibleView.height + topDecorations + bottomDecorations
        val decoratedWidth: Int = firstVisibleView.width + leftDecorations + rightDecorations
        val isHorizontal: Boolean =
            mLayoutManager.orientation == ViewPager2.ORIENTATION_HORIZONTAL
        var start: Int
        val sizePx: Int
        if (isHorizontal) {
            sizePx = decoratedWidth
            start = firstVisibleView.left - leftDecorations - mRecyclerView.paddingLeft
            if ((mViewPager.layoutDirection == LAYOUT_DIRECTION_RTL)) {
                start = -start
            }
        } else {
            sizePx = decoratedHeight
            start = firstVisibleView.top - topDecorations - mRecyclerView.paddingTop
        }
        values.mOffsetPx = -start
        if (values.mOffsetPx < 0) {
            // We're in an error state. Figure out if this might have been caused
            // by animateLayoutChanges and throw a descriptive exception if so
            throw IllegalStateException(
                String.format(
                    Locale.US, ("Page can only be offset by a "
                            + "positive amount, not by %d"), values.mOffsetPx
                )
            )
        }
        values.mOffset = if (sizePx == 0) 0f else values.mOffsetPx.toFloat() / sizePx
    }

    private fun startDrag(isFakeDrag: Boolean) {
        isFakeDragging = isFakeDrag
        mAdapterState =
            if (isFakeDrag) STATE_IN_PROGRESS_FAKE_DRAG else STATE_IN_PROGRESS_MANUAL_DRAG
        if (mTarget != NO_POSITION) {
            // Target was set means we were settling to that target
            // Update "drag start page" to reflect the page that ViewPager2 thinks it is at
            mDragStartPosition = mTarget
            // Reset target because drags have no target until released
            mTarget = NO_POSITION
        } else if (mDragStartPosition == NO_POSITION) {
            // ViewPager2 was at rest, set "drag start page" to current page
            mDragStartPosition = position
        }
        dispatchStateChanged(ViewPager2.SCROLL_STATE_DRAGGING)
    }

    fun notifyDataSetChangeHappened() {
        mDataSetChangeHappened = true
    }

    /**
     * Let the adapter know a programmatic scroll was initiated.
     */
    fun notifyProgrammaticScroll(target: Int, smooth: Boolean) {
        mAdapterState =
            if (smooth) STATE_IN_PROGRESS_SMOOTH_SCROLL else STATE_IN_PROGRESS_IMMEDIATE_SCROLL
        // mFakeDragging is true when a fake drag is interrupted by an a11y command
        // set it to false so endFakeDrag won't fling the RecyclerView
        isFakeDragging = false
        val hasNewTarget: Boolean = mTarget != target
        mTarget = target
        dispatchStateChanged(ViewPager2.SCROLL_STATE_SETTLING)
        if (hasNewTarget) {
            dispatchSelected(target)
        }
    }

    /**
     * Let the adapter know that a fake drag has started.
     */
    fun notifyBeginFakeDrag() {
        mAdapterState = STATE_IN_PROGRESS_FAKE_DRAG
        startDrag(true)
    }

    /**
     * Let the adapter know that a fake drag has ended.
     */
    fun notifyEndFakeDrag() {
        if (isDragging && !isFakeDragging) {
            // Real drag has already taken over, no need to post process the fake drag
            return
        }
        isFakeDragging = false
        updateScrollEventValues()
        if (mScrollValues.mOffsetPx == 0) {
            // We're snapped, so dispatch an IDLE event
            if (mScrollValues.mPosition != mDragStartPosition) {
                dispatchSelected(mScrollValues.mPosition)
            }
            dispatchStateChanged(ViewPager2.SCROLL_STATE_IDLE)
            resetState()
        } else {
            // We're not snapped, so dispatch a SETTLING event
            dispatchStateChanged(ViewPager2.SCROLL_STATE_SETTLING)
        }
    }

    fun setOnPageChangeCallback(callback: OnPageChangeCallback?) {
        mCallback = callback
    }

    /**
     * @return `true` if there is no known scroll in progress
     */
    val isIdle: Boolean
        get() = scrollState == ViewPager2.SCROLL_STATE_IDLE

    /**
     * @return `true` if the ViewPager2 is being dragged. Returns `false` from the
     * moment the ViewPager2 starts settling or goes idle.
     */
    val isDragging: Boolean
        get() = scrollState == ViewPager2.SCROLL_STATE_DRAGGING

    /**
     * Checks if the adapter state (not the scroll state) is in the manual or fake dragging state.
     * @return `true` if [.mAdapterState] is either [         ][.STATE_IN_PROGRESS_MANUAL_DRAG] or [.STATE_IN_PROGRESS_FAKE_DRAG]
     */
    private val isInAnyDraggingState: Boolean
        private get() = (mAdapterState == STATE_IN_PROGRESS_MANUAL_DRAG
                || mAdapterState == STATE_IN_PROGRESS_FAKE_DRAG)

    /**
     * Calculates the scroll position of the currently visible item of the ViewPager relative to its
     * width. Calculated by adding the fraction by which the first visible item is off screen to its
     * adapter position. E.g., if the ViewPager is currently scrolling from the second to the third
     * page, the returned value will be between 1 and 2. Thus, non-integral values mean that the
     * the ViewPager is settling towards its [current item][ViewPager2.getCurrentItem], or
     * the user may be dragging it.
     *
     * @return The current scroll position of the ViewPager, relative to its width
     */
    val relativeScrollPosition: Double
        get() {
            updateScrollEventValues()
            return mScrollValues.mPosition + mScrollValues.mOffset.toDouble()
        }

    private fun dispatchStateChanged(@ScrollState state: Int) {
        // Callback contract for immediate-scroll requires not having state change notifications,
        // but only when there was no smooth scroll in progress.
        // By putting a suppress statement in here (rather than next to dispatch calls) we are
        // simplifying the code of the class and enforcing the contract in one place.
        if ((mAdapterState == STATE_IN_PROGRESS_IMMEDIATE_SCROLL
                    && scrollState == ViewPager2.SCROLL_STATE_IDLE)
        ) {
            return
        }
        if (scrollState == state) {
            return
        }
        scrollState = state
        if (mCallback != null) {
            mCallback!!.onPageScrollStateChanged(state)
        }
    }

    private fun dispatchSelected(target: Int) {
        if (mCallback != null) {
            mCallback!!.onPageSelected(target)
        }
    }

    private fun dispatchScrolled(position: Int, offset: Float, offsetPx: Int) {
        if (mCallback != null) {
            mCallback!!.onPageScrolled(position, offset, offsetPx)
        }
    }

    private val position: Int
        private get() {
            return mLayoutManager.findFirstVisibleItemPosition()
        }

    private class ScrollEventValues  // to avoid a synthetic accessor
    internal constructor() {
        var mPosition: Int = 0
        var mOffset: Float = 0f
        var mOffsetPx: Int = 0
        fun reset() {
            mPosition = RecyclerView.NO_POSITION
            mOffset = 0f
            mOffsetPx = 0
        }
    }

    companion object {
        private const val STATE_IDLE: Int = 0
        private const val STATE_IN_PROGRESS_MANUAL_DRAG: Int = 1
        private const val STATE_IN_PROGRESS_SMOOTH_SCROLL: Int = 2
        private const val STATE_IN_PROGRESS_IMMEDIATE_SCROLL: Int = 3
        private const val STATE_IN_PROGRESS_FAKE_DRAG: Int = 4
        private const val NO_POSITION: Int = -1
    }

    init {
        mLayoutManager = (mRecyclerView.layoutManager as LinearLayoutManager?)!!
        mScrollValues = ScrollEventValues()
        resetState()
    }
}
```

**Comment by ChairfaceChippendale** [comment]
Faced the same issue. Upgrading 
```
'androidx.constraintlayout:constraintlayout:2.0.0-beta6'
'com.google.android.material:material:1.2.0-alpha06'
```
fixed the problem.

**Comment by slavonnet** [comment]
This becouse code use
View.searchFocus() and it use parent.searchFocus(this, direction). But parent is FrameLayout
if i use parent.parent.searchFocus its work ok!

this hack ))


                val a: TextInputLayout = view.parent.parent as TextInputLayout

```
                if (a.editText?.imeOptions != IME_ACTION_NEXT && a.editText?.isSingleLine == true)
                    a.editText?.imeOptions = IME_ACTION_NEXT

                if (a.focusSearch(view, ViewGroup.FOCUS_FORWARD).id == -1)
                    a.focusSearch(view, ViewGroup.FOCUS_FORWARD).id = ViewCompat.generateViewId()

                a.editText?.nextFocusForwardId = a.focusSearch(view, ViewGroup.FOCUS_FORWARD).id

```

**Comment by AlmightyCZ** [comment]
> This is still happening when com.google.android.material.textfield.TextInputLayout used inside viewpager2 based on recyclerview.
> Its not only inputType number, but for all inputTypes on first focus and when focus change from one TextInputEditText to another TextInputEditText with different inputTypes, then the focus is lost when keyboard shows up.
> 
> "com.google.android.material:material:1.2.0-alpha01"
> "androidx.viewpager2:viewpager2:1.0.0"

I can confirm this problem, I have three pages all with constraintlayout, one has just some labels, the second is a form of TextInputLayouts, the third contains RecyclerView.
'com.google.android.material:material:1.3.0-alpha01'
'androidx.viewpager2:viewpager2:1.1.0-alpha01'
'androidx.constraintlayout:constraintlayout:2.0.0-beta8'

After a page change (by user input or programatically), the first focus (again user input, or programatically, no matter the delay after page change), causes onPageSelected call of pager's internal listener that clears this focus. 
I can workaround this for the focus requested from code by calling another posted requestFocus right after the first one, however this cancels the animation and it doesn't look good. This also solves the user input case, since I do it in the onResume of the page fragment and all the user interaction happens after this point.

**Comment by hunterstich** [comment]
Hey @devqmr, @ChairfaceChippendale, @AlmightyCZ 

Any chance someone is able to provide a small sample that reproduces this in order to help us debug and work on a fix? It's extremely helpful when we don't have to set up a project and things for each issue we receive! 

Thanks!

**Comment by AlmightyCZ** [comment]
Hey @hunterstich it can be replicated using my old sample, that I made for a different ViewPager2 bug report. I just updated the libraries to current version. https://github.com/AlmightyCZ/ViewPager2TextInputGravity
When I start the app, switch to the FORM tab and then try to focus editor, it just opens the keyboard, but the editor still appears as unfocused and input from the keyboard is ignored. When you then try to focus editor again it works fine. But if you then change to another tab and back to FORM tab, the whole thing happens again. (this time you can even see the animation of editText getting focus immediately followed of loosing focus animation.
This described behaviour is for Android 6 tablet. When I run on Android 10 phone, it's similar, but in this case the input from the keyboard is not ignored and causes editText to regain focus.

**Comment by schlagi123** [comment]
This issue is a general issue and not specific to the material components. (s. https://github.com/android/views-widgets-samples/issues/107)

If you have a small number of pages there is the workaround to increase the `offscreenPageLimit` of the `ViewPager2` (thanks to @FEvgenSON https://github.com/android/views-widgets-samples/issues/107#issuecomment-726809766)

**Comment by drchen** [comment]
Given the above comment, I'll close the issue as infeasible as it seems like a material issue and there's a workaround for it. 

Feel free to reopen it if you figure out anything we can fix on our end. Thanks!!

**Comment by ovcharenkoa** [comment]
I meet the issue again. I searched for about 1 h on how to solve it and while not found the track of the issue. I solved the issue, just migrate to View Pager. No more easy way to solve the issue.
