### ISSUE TITLE
HTML Option crashes the WebView on Android 6

### ISSUE THREAD

**Issue by gabrielecuccu** [material-components/material-components-android#990]
**Description:** On Android 6, within a WebView, using com.google.android.material:material
 version >= 1.1.0, the render of an html option will crash the app.
This doesn't happen on Android > 6.

**Expected behaviour:** HTML Option should be rendered without crashing the app.

**Source code:** 
```
<form>
	<select>
		<option>Option One</option>
		<option>Option Two</option>
	</select>
</form>
```

**Android API version:** 23

**Material Library version:** 1.1.0-alpha06, 1.2.0-alpha04, any > 1.0.0.

**Device:** SAMSUNG-SM-G900V (or any running Android 6).

**Stacktrace:**
02-06 14:18:31.467 930-930/com.ft.news E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ft.news, PID: 930
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.Resources.getValue(Resources.java:2558)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:4360)
        at android.content.res.Resources.getLayout(Resources.java:2372)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:378)
        at android.widget.ArrayAdapter.getView(ArrayAdapter.java:369)
        at Hv.getView(PG:13)
        at android.widget.AbsListView.obtainView(AbsListView.java:2929)
        at android.widget.ListView.measureHeightOfChildren(ListView.java:1305)
        at android.widget.ListView.onMeasure(ListView.java:1212)
        at android.view.View.measure(View.java:20151)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:20151)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:20151)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
        at android.view.View.measure(View.java:20151)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:20151)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:20151)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3158)
        at android.view.View.measure(View.java:20151)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2594)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1524)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1841)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
        at android.view.Choreographer.doCallbacks(Choreographer.java:695)
        at android.view.Choreographer.doFrame(Choreographer.java:631)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by cketcham** [comment]
It seems there is a bug with the version of appcompat that we have as a dependency for those versions. I also found http://issuetracker.google.com/issues/134610936 which looks to be a duplicate.

If you want to fix it for those versions of our library you can force it to use a newer version of the appcompat library by adding `implementation 'androidx.appcompat:appcompat:1.2.0-alpha02'` to your dependencies. It seems that at that version the crash is no longer happening.

**Comment by gabrielecuccu** [comment]
Thank you for your reply. Unfortunately upgrading appcompat to 1.2.0-alpha02 doesn't fix this.
I also tried with the latest material (1.2.0-alpha04) but the crash is still there, same stacktrace.

**Comment by cketcham** [comment]
I have a sample where I'm using 1.2.0-alpha04 of the material library. Running the sample will cause a crash when I click on the select in the webview. After adding `implementation 'androidx.appcompat:appcompat:1.2.0-alpha02'` to the apps deps it is fixed.

I also tried 1.1.0 with the same result.

But it does seem like something weird is going on related to resources here... so maybe there's a more obscure bug and updating the version of appcompat just happens to fix it for me? Could you create a sample project that I can use to reproduce the crash even when adding the updated appcompat dep?

**Comment by gabrielecuccu** [comment]
Yes I can provide a sample project. Di you test your sample on Android 6?

**Comment by cketcham** [comment]
Yes I did run it on Android 6. It was crashing so I did observe the behavior you describe. But then stops crashing when I update the appcompat dep.

**Comment by gabrielecuccu** [comment]
My sample project works exactly as you say: app-compat 1.2.0-alpha02 fixes the crash.
Unfortunately this is not true in my production app, that still crashes with the same stack-trace.
I don't know what is going on here but I've decided to give up new features (like exposed dropdown lists) and to stick with material design 1.0.0 which works fine.

**Comment by cketcham** [comment]
Since it seems this is an issue in appcompat and we can't figure out how to consistently reproduce the error I'm going to close this. If we learn more we can re-open it.

**Comment by cketcham** [comment]
If you want more information, it looks like this is the bug that was fixed in 1.2.0-alpha02 of appcompat: http://issuetracker.google.com/issues/141351441

**Comment by eyedol** [comment]
Faced a similar issue and it's coming from appcompat v1.1.0 which is shipped with `material-components`. However, there's a potential fix for certain cases here https://stackoverflow.com/a/58355733
